pipeline {
    agent { label 'java-node' }

    tools {
        jdk 'java17'
        maven 'maven-3'
    }

    environment {
        IMAGE_NAME = "rishikumarandugala/api-gateway"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Clone Repository') {
            steps {
                deleteDir()   // 🔥 clean workspace (important)
                git branch: 'main', url: 'https://github.com/Rishikumar123456789/banking-system.git'
            }
        }

        stage('Build Eureka Server') {
            steps {
                dir('api-gateway') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('api-server') {
                    sh 'docker build -t $IMAGE_NAME:$IMAGE_TAG .'
                }
            }
        }

        stage('Login to DockerHub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                }
            }
        }

        stage('Push Image to DockerHub') {
            steps {
                sh 'docker push $IMAGE_NAME:$IMAGE_TAG'
            }
        }

        stage('Deploy to Kubernetes using Helm') {
            steps {
                dir('api-gateway') {
                    sh '''
                    echo "📦 Checking Helm chart..."
                    ls -l helm/config-server-chart

                    helm upgrade --install api-gateway helm/api-gateway-chart \
                    --set image.repository=$IMAGE_NAME \
                    --set image.tag=$IMAGE_TAG
                    '''
                }
            }
        }
    }

    post {
        success {
            echo "✅ Deployment successful! Kubernetes updated with new Docker image."
        }
        failure {
            echo "❌ Pipeline failed. Please check Jenkins logs."
        }
    }
}