replicaCount: 2

image:
  repository: rishikumarandugala/eureka-server
  tag: "1.0"
  pullPolicy: IfNotPresent

containerPort: 8761

service:
  type: ClusterIP
  port: 8761
  targetPort: 8761

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"